### ISSUE TITLE
Unhandled Exception System.InvaledOperationException

### ISSUE THREAD

**Issue by Derpmaster45** [Derpmaster45/silver-lamp#19]
An unhandled exception of type 'System.InvalidOperationException' occurred in System.Console.dll: 'Cannot read keys when either application does not have a console or when console input has been redirected. Try Console.Read.'
   at System.ConsolePal.ReadKey(Boolean intercept)
   at DH4.Game.<Main>g__PromptedClearScreen|0_3() in /home/jay/Documents/silver-lamp/Program.cs:line 76
   at DH4.Game.Main(String[] args) in /home/jay/Documents/silver-lamp/Program.cs:line 197

**Comment by Derpmaster45** [comment]
{System.InvalidOperationException: Cannot read keys when either application does not have a console or when console input has been redirected. Try Console.Read.
   at System.ConsolePal.ReadKey(Boolean intercept)
   at DH4.Game.<Main>g__PromptedClearScreen|0_3() in /home/jay/Documents/silver-lamp/Program.cs:line 76
   at DH4.Game.Main(String[] args) in /home/jay/Documents/silver-lamp/Program.cs:line 197}

**Comment by Derpmaster45** [comment]
used Console.Read. to keep it from throwing the exception
